### ISSUE TITLE
3.5 jack question

### ISSUE THREAD

**Issue by antonpodkur** [Olasergiolas/R9-380-RyzenHackintosh#1]
Hello, I have the same motherboard as yours.
Everything works fine, except 3.5 mm microphone. I just want to ask you, whether your 3.5 mm micro is working if you are using one. Thanks in advance!

**Comment by Olasergiolas** [comment]
> Hello, I have the same motherboard as yours. Everything works fine, except 3.5 mm microphone. I just want to ask you, whether your 3.5 mm micro is working if you are using one. Thanks in advance!

I'm afraid this is a well known problem on AMD hackintoshes and there isn't a proper solution aside from changing your audio kext at the cost of losing stability and audio quality :(.

Check [this](https://dortania.github.io/OpenCore-Post-Install/universal/audio.html#no-mic-on-amd) out for more info on how to solve it.
